name: test

on:
  workflow_dispatch: {}
  pull_request: {}
  push: { branches: ["main"] }

jobs:
  test-action:
    name: "Test setup-kusto on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout composite actions repository
        uses: actions/checkout@v3.5.2
        with:
          repository: philip-gai/setup-kusto
          path: setup-kusto
          ref: ${{ github.ref }}
      - name: Setup Kusto
        uses: ./setup-kusto
