name: test

on:
  workflow_dispatch: {}
  pull_request: {}
  push: { branches: ["main"] }

jobs:
  test-action:
    name: "Test setup-kusto on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: "2.1.x"
      - name: Run ${{github.repository}}
        uses: ./
      - run: dotnet --version
      - name: "Display CLI help synopsis"
        run: dotnet "${{ env.KUSTO_CLI_PATH }}"
      - name: "Connect to help cluster"
        run: dotnet "${{ env.KUSTO_CLI_PATH }}" "https://help.kusto.windows.net/Samples;Fed=true"
