name: test

on:
  workflow_dispatch: {}
  pull_request: {}
  push: { branches: ["main"] }

jobs:
  test-action:
    name: "Test setup-kusto on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./
