name: test

on:
  workflow_dispatch: {}
  pull_request: {}
  push: { branches: ["main"] }

jobs:
  test-action:
    name: "Test setup-kusto on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        inputs:
          [
            { kusto-version: "7.2.1", target-version: net6.0 },
            { kusto-version: "11.3.1", target-version: net6.0 },
          ]
    steps:
      - uses: actions/checkout@v3.5.2
      - name: Run ${{github.repository}} with ${{ matrix.inputs.kusto-version }} on ${{ matrix.inputs.target-version }}
        uses: ./
        with:
          kusto-version: ${{ matrix.inputs.kusto-version }}
          target-version: ${{ matrix.inputs.target-version }}
      - name: "Test #help"
        run: dotnet "${{ env.KUSTO_CLI_PATH }}" -execute:"#help"
        shell: bash
